### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/Grove_3_Axis_Compass_BMM150#3]
The Wire.endTransmission() and Wire.beginTransmission() should not be used together with Wire.requestFrom().

Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.

**Comment by lanselambor** [comment]
Thanks and it was corrected now.
