### ISSUE TITLE
Will this give me a tilt compensated compass heading ? 

### ISSUE THREAD

**Issue by amansinghaljpr** [Seeed-Studio/Grove_3_Axis_Compass_BMM150#4]
After reading your code there seems to be a confusion , i am not sure weather it will help me to give a 2d compass heading or a 3d compass heading . 

    `float headingDegrees = heading * 180 / M_PI;
    float xyHeadingDegrees = xyHeading * 180 / M_PI;
    float zxHeadingDegrees = zxHeading * 180 / M_PI;

    Serial.print("Heading: ");
    Serial.println(headingDegrees);`

Looking at this you are performing calculations for both xy axis and yz axis but while printing you are only accounting for xy axis

**Comment by orichienal** [comment]
i am also after a solution.
I also have a gy521.
maybe he can help.

**Comment by lakshanthad** [comment]
Hello,

I have pushed a commit. Please check here:
https://github.com/Seeed-Studio/Grove_3_Axis_Compass_V2.0_BMM150/commit/de221d7360eeeb564160946f0cd2c8b3fb448040

Thank you

**Comment by ackPeng** [comment]
@amansinghaljpr @orichienal Do you still have doubts about this now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
