### ISSUE TITLE
BMM150.h is incompatible with Arduino Cloud

### ISSUE THREAD

**Issue by harryga** [Seeed-Studio/Grove_3_Axis_Compass_BMM150#6]
My sketch ('compass.ino' example) stops when I try to access the BMM150 libraries in Arduino Cloud. All works as expected outside the cloud. Yes, I have implemented the recommended sketch structure for I2C devices in Setup. Any attempt to access the BMM150 within the sketch in Arduino Cloud causes the program to halt. If I comment out the statements, the sketch continues. Sketch installed on a generic ESP32-wroom-32.

**Comment by ackPeng** [comment]
Is your I2C initialization completed? On the other hand, are the resources occupied by Arduino Cloud conflicting with other resources?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
